### ISSUE TITLE
Servlet context is not picked up

### ISSUE THREAD

**Issue by fbiville** [vidal-community/jax-rs-linker#41]

**Comment by nicokosi** [comment]
Issue occurred with Jetty 9 v20150310 (http://download.eclipse.org/jetty/stable-9/dist/jetty-distribution-9.2.10.v20150310.zip) on a Windows 8 machine (but not on my Linux machine).
I forgot to keep the Java stack trace. :-/

**Comment by nicokosi** [comment]
Issue also occurred with Tomcat 8. :disappointed: :panda_face: 
Stack trace is:

> INFO   | jvm 1    | 2015/04/08 14:58:56 | 2015-04-08 14:58:56.122 ERROR 4312 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/pmsi]   : Exception sending context initialized event to listener instance of class fr.vidal.oss.jax_rs_linker.Linkers
INFO   | jvm 1    | 2015/04/08 14:58:56 | 
INFO   | jvm 1    | 2015/04/08 14:58:56 | java.util.NoSuchElementException: null
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1431)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at fr.vidal.oss.jax_rs_linker.servlet.ContextPaths.contextPath(ContextPaths.java:8)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at fr.vidal.oss.jax_rs_linker.Linkers.contextInitialized(Linkers.java:24)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2015/04/08 14:58:56 | 	at java.lang.Thread.run(Thread.java:745)

**Comment by fbiville** [comment]
Reproduit encore aujourd'hui sur une VM Ubuntu 32 bits en utilisant l'installeur PMSI.
StackO : http://stackoverflow.com/questions/29629992/mapping-conflict-when-deploying-with-spring-boot-jersey-starter-deployed-as-war.

**Comment by fbiville** [comment]
Workaround: we can avoid crashing and add a configurable default path.

**Comment by fbiville** [comment]
Issue has been filed https://github.com/spring-projects/spring-boot/issues/3028.

**Comment by malk** [comment]
Fixed by the workaround on #45
