### ISSUE TITLE
Adding a subresource to a classic ressource (without self) fails silently

### ISSUE THREAD

**Issue by malk** [vidal-community/jax-rs-linker#50]
Adding a subresource to a classic ressource (without self) fails silently
it does not compile at all
but bears no error message

**Comment by fbiville** [comment]
We could explicitly trigger an error msg here: https://github.com/vidal-community/jax-rs-linker/blob/master/jax-rs-linker/src/main/java/fr/vidal/oss/jax_rs_linker/writer/LinkerWriter.java#L62.
