### ISSUE TITLE
Handle List & Set query parameter

### ISSUE THREAD

**Issue by mgazanayi** [vidal-community/jax-rs-linker#57]
When we have query parameters as `List` or `Set`, we manually generate query parameter values to be exactly the same as the original url:

Example:
When `@QueryParam` is a `Set` then we need to construct an url like this `/rest/api/alerts?productId=1&productId=2&vmpId=1&vmpId=3&vmpId=23&cngId=2`
or
When `@QueryParam` is a `List` then we need to construct an url like this `/rest/api/alerts?productId=1,2&vmpId=1,3,23&cngId=2`

The only tool provided by Jax-rs-linker is: `all.relatedApiAlertsResourceInteractions().append(ApiAlertsResourceQueryParameters.PRODUCT_ID, "1,2")` and this works only for List query params
For Set, we have to call `append` twice : 
 `all.relatedApiAlertsResourceInteractions().append(PRODUCT_ID, "1").append(PRODUCT_ID, "1")`

We would very welcome something like : 

```
all.relatedApiAlertsResourceInteractions().append(ApiAlertsResourceQueryParameters.PRODUCT_ID, newArrayList(1,2))
```

and 

```
all.relatedApiAlertsResourceInteractions().append(ApiAlertsResourceQueryParameters.PRODUCT_ID, newHashSet(1,2))
```

**Comment by fbiville** [comment]
I'm not sure to see why `List` would necessarily imply a single parameter with comma-separated values. 
I would rather leave the choice to the user when you call `value()`.

You could either:

 1. do nothing (after all, there is already away to achieve what you want)
 2. introduce an overload of `value` with a new parameter with possibles enumerations like `REPEATED_PARAMETER` and `SINGLE_PARAMETER`

I'd favor "solution" 1.

After all, once you go down the rabbit hole of solution 2, then, what about end users that need other separators than comma? What about specific syntax like `param[]=foo&param[]=bar`...?

I'm making some stuff up, but solution 1 already works and is flexible.
Achieving the same degree of flexibility with solution 2 requires a lot more work than the draft description I offered above.

**Comment by mgazanayi** [comment]
Ok for solution 1, after all, appending many times isn't too hard to achieve.
